apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-microservice
spec:
  ingressClassName: nginx
  rules:
  - host: otus.homework
    http:
      paths:
      - path: "/health/"
        pathType: Prefix
        backend:
          service:
            name: svc-microsevice
            port: 
              number: 80
