apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-microsevices
spec:
  replicas: 2
  selector:
    matchLabels:
      env: rs-microsevice
  template:
    metadata:
      labels:
        env: rs-microsevice
    spec:
      containers:
      - name: hello-microsevice-v3
        image: damirnr/microsevice_v3